vim.opt.rtp:prepend(vim.fn.expand("~/.config/nvim/plugins/neo-tree/"))

require("neo-tree").setup {
    sources = {
        "filesystem",
        "buffers",
    },
    add_blank_line_at_top = false,
    auto_clean_after_session_restore = false,
    clipboard = {
        sync = "none",
    },
    close_if_last_window = false,
    default_source = "filesystem",
    enable_diagnostics = true,
    enable_modified_markers = true,
    enable_opened_markers = true,
    enable_refresh_on_write = true,
    enable_cursor_hijack = true,
    hide_root_node = false,
    retain_hidden_root_indent = false,
    keep_altfile = false,
    log_level = vim.log.levels.INFO,
    log_to_file = false,
    open_files_in_last_window = true,
    open_files_do_not_replace_types = { "terminal", "Trouble", "qf", "edgy" },
    open_files_using_relative_paths = false,
    popup_border_style = "single",
    resize_timer_interval = 500,
    sort_case_insensitive = false,
    sort_function = nil,
    use_popups_for_input = true,
    use_default_mappings = true,
    source_selector = {
        winbar = false,
        statusline = false,
        show_scrolled_off_parent_node = false,
        sources = {
            { source = "filesystem" },
            { source = "buffers" },
        },
        content_layout = "start",
        tabs_layout = "equal",
        truncation_character = "...",
        tabs_min_width = nil,
        tabs_max_width = nil,
        padding = 0,
        separator = { left = "▏", right = "▕" },
        separator_active = nil,
        show_separator_on_edge = false,
        highlight_tab = "NeoTreeTabInactive",
        highlight_tab_active = "NeoTreeTabActive",
        highlight_background = "NeoTreeTabInactive",
        highlight_separator = "NeoTreeTabSeparatorInactive",
        highlight_separator_active = "NeoTreeTabSeparatorActive",
    },
    default_component_configs = {
        container = {
            enable_character_fade = true,
            width = "100%",
            right_padding = 0,
        },
        indent = {
            indent_size = 4,
            padding = 1,
            with_markers = true,
            indent_marker = "│",
            last_indent_marker = "└",
            highlight = "NeoTreeIndentMarker",
            with_expanders = nil,
            expander_collapsed = "",
            expander_expanded = "",
            expander_highlight = "NeoTreeExpander",
        },
        icon = {
            folder_closed = "",
            folder_open = "",
            folder_empty = "󰉖",
            folder_empty_open = "󰷏",
            use_filtered_colors = true,
            default = "*",
            highlight = "NeoTreeFileIcon",
            provider = function(icon, node, state)
                if node.type == "file" or node.type == "terminal" then
                    local success, web_devicons = pcall(require, "nvim-web-devicons")
                    local name = node.type == "terminal" and "terminal" or node.name
                    if success then
                        local devicon, hl = web_devicons.get_icon(name)
                        icon.text = devicon or icon.text
                        icon.highlight = hl or icon.highlight
                    end
                end
            end,
        },
        modified = {
            symbol = "[+] ",
            highlight = "NeoTreeModified",
        },
        name = {
            trailing_slash = true,
            highlight_opened_files = true,
            use_filtered_colors = true,
            use_git_status_colors = false,
            highlight = "NeoTreeFileName",
        },
        file_size = {
            enabled = false,
            width = 12,
            required_width = 64,
        },
        type = {
            enabled = false,
            width = 10,
            required_width = 110,
        },
        last_modified = {
            enabled = false,
            width = 20,
            required_width = 88,
            format = "%Y-%m-%d %I:%M %p",
        },
        created = {
            enabled = false,
            width = 20,
            required_width = 120,
            format = "%Y-%m-%d %I:%M %p",
        },
        symlink_target = {
            enabled = false,
            target_display = "force_absolute",
            text_format = " ➛ %s",
        },
    },
    renderers = {
        directory = {
            { "indent" },
            { "icon" },
            { "current_filter" },
            {
                "container",
                content = {
                    { "name", zindex = 10 },
                    {
                        "symlink_target",
                        zindex = 10,
                        highlight = "NeoTreeSymbolicLinkTarget",
                    },
                    { "clipboard", zindex = 10 },
                    { "diagnostics", errors_only = true, zindex = 20, align = "right", hide_when_expanded = true },
                    { "git_status", zindex = 10, align = "right", hide_when_expanded = true },
                    { "file_size", zindex = 10, align = "right" },
                    { "type", zindex = 10, align = "right" },
                    { "last_modified", zindex = 10, align = "right" },
                    { "created", zindex = 10, align = "right" },
                },
            },
        },
        file = {
            { "indent" },
            { "icon" },
            {
                "container",
                content = {
                    {
                        "name",
                        zindex = 10,
                    },
                    {
                        "symlink_target",
                        zindex = 10,
                        highlight = "NeoTreeSymbolicLinkTarget",
                    },
                    { "clipboard", zindex = 10 },
                    { "bufnr", zindex = 10 },
                    { "modified", zindex = 20, align = "right" },
                    { "diagnostics", zindex = 20, align = "right" },
                    { "git_status", zindex = 10, align = "right" },
                    { "file_size", zindex = 10, align = "right" },
                    { "type", zindex = 10, align = "right" },
                    { "last_modified", zindex = 10, align = "right" },
                    { "created", zindex = 10, align = "right" },
                },
            },
        },
        message = {
            { "indent", with_markers = false },
            { "name", highlight = "NeoTreeMessage" },
        },
        terminal = {
            { "indent" },
            { "icon" },
            { "name" },
            { "bufnr" },
        },
    },
    nesting_rules = {},
    commands = {},
    window = {
        position = "left",
        width = 40,
        height = 15,
        auto_expand_width = false,
        popup = {
            size = {
                height = "80%",
                width = "50%",
            },
            position = "50%",
            title = function(state)
                return "Neo-tree " .. state.name:gsub("^%l", string.upper)
            end,
        },
        insert_as = "child",
        mapping_options = {
            noremap = true,
            nowait = true,
        },
        mappings = {},
    },
    filesystem = {
        window = {
            mappings = {},
            fuzzy_finder_mappings = {},
        },
        async_directory_scan = "auto",
        scan_mode = "shallow",
        bind_to_cwd = true,
        cwd_target = {
            sidebar = "tab",
            current = "window",
        },
        check_gitignore_in_search = true,
        filtered_items = {
            visible = false,
            force_visible_in_empty_folder = false,
            children_inherit_highlights = true,
            show_hidden_count = true,
            hide_dotfiles = true,
            hide_gitignored = false,
            hide_ignored = true,
            ignore_files = {},
            hide_hidden = true,
            hide_by_name = {},
            hide_by_pattern = {},
            always_show = {},
            always_show_by_pattern = {},
            never_show = {},
            never_show_by_pattern = {},
        },
        find_by_full_path_words = false,
        group_empty_dirs = false,
        search_limit = 50,
        follow_current_file = {
            enabled = false,
            leave_dirs_open = false,
        },
        hijack_netrw_behavior = "open_default",
        use_libuv_file_watcher = false,
    },
    buffers = {
        bind_to_cwd = true,
        follow_current_file = {
            enabled = true,
            leave_dirs_open = false,
        },
        group_empty_dirs = true,
        show_unloaded = false,
        terminals_first = false,
        window = {
            mappings = {},
        },
    },
    git_status = {
        window = {},
    },
    document_symbols = {
        follow_cursor = false,
        client_filters = "first",
        renderers = {
            root = {
                { "indent" },
                { "icon", default = "C" },
                { "name", zindex = 10 },
            },
            symbol = {
                { "indent", with_expanders = true },
                { "kind_icon", default = "?" },
                {
                    "container",
                    content = {
                        { "name", zindex = 10 },
                        { "kind_name", zindex = 20, align = "right" },
                    },
                },
            },
        },
        window = {
            mappings = {},
        },
        custom_kinds = {},
        kinds = {
            Unknown = { icon = "?", hl = "" },
            Root = { icon = "", hl = "NeoTreeRootName" },
            File = { icon = "󰈙", hl = "Tag" },
            Module = { icon = "", hl = "Exception" },
            Namespace = { icon = "󰌗", hl = "Include" },
            Package = { icon = "󰏖", hl = "Label" },
            Class = { icon = "󰌗", hl = "Include" },
            Method = { icon = "", hl = "Function" },
            Property = { icon = "󰆧", hl = "@property" },
            Field = { icon = "", hl = "@field" },
            Constructor = { icon = "", hl = "@constructor" },
            Enum = { icon = "󰒻", hl = "@number" },
            Interface = { icon = "", hl = "Type" },
            Function = { icon = "󰊕", hl = "Function" },
            Variable = { icon = "", hl = "@variable" },
            Constant = { icon = "", hl = "Constant" },
            String = { icon = "󰀬", hl = "String" },
            Number = { icon = "󰎠", hl = "Number" },
            Boolean = { icon = "", hl = "Boolean" },
            Array = { icon = "󰅪", hl = "Type" },
            Object = { icon = "󰅩", hl = "Type" },
            Key = { icon = "󰌋", hl = "" },
            Null = { icon = "", hl = "Constant" },
            EnumMember = { icon = "", hl = "Number" },
            Struct = { icon = "󰌗", hl = "Type" },
            Event = { icon = "", hl = "Constant" },
            Operator = { icon = "󰆕", hl = "Operator" },
            TypeParameter = { icon = "󰊄", hl = "Type" },
        },
    },
}