[General]
appdatadir=/home/abdul/.config/Meltytech/
askUpgradeAutomatic=false
backupPeriod=0
checkUpgradeAutomatic=false
clearRecent=false
convertAdvanced=true
exportRangeMarkers=false
flatpakWrappers=false
imageDuration=15
jobPriority=normal
language=en_GB
noupgrade=true
openPath=/home/abdul/
opengl=0
processingMode=0
projectsFolder=/home/abdul/
savePath=/home/abdul/
showConvertClipDialog=true
theme=dark
timeFormat=1
titleBars=true
toolBar=true
undoLimit=300
warnLowMemory=true

[encode]
advanced=false
freeSpaceCheck=true
hardwareDecoder=true
path=/home/abdul/
useHardware=true

[files]
foldersOpen=true
viewMode=detailed

[filter]
askOutput=true
audioInCurve=1
audioOutCurve=1

[keyframes]
dragScrub=false

[markers]
color=green
columns/color=true
columns/duration=true
columns/end=true
columns/start=true
columns/text=true
sortColumn=4
sortOrder=0

[player]
gpu2=true
interpolation=nearest
jack=false
keyer=0
muted=true
pauseAfterSeek=true
previewHardwareDecoder=true
progressive=false
realtime=true
scrubAudio=false
videoDelayMs=0
volume=0
warnGPU=true
zoom=0

[playlist]
autoplay=false
columns/clip=true
columns/date=true
columns/in=true
columns/start=true
columns/thumbnails=true
columns/duration=true
previewScale=360
thumbnails=small
viewMode=detailed

[scope]
loudness/integrated=true
loudness/momentary=true
loudness/peak=true
loudness/range=true
loudness/shortterm=true
loudness/truepeak=true

[shortcuts]
newProject=Ctrl+N
openProject=Ctrl+O
saveProject=Ctrl+S
saveAsProject=Ctrl+Shift+S
closeProject=Ctrl+W
quitApp=Ctrl+Q
undo=Ctrl+Z
redo=Ctrl+Y
cut=Ctrl+X
copy=Ctrl+C
paste=Ctrl+V
selectAll=Ctrl+A
delete=Backspace
nextFrame=Right
previousFrame=Left
zoomIn=Ctrl+=
zoomOut=Ctrl+-
zoomFit=Ctrl+0