[general]
working_directory = "/home/abdul"
ipc_socket = true
live_config_reload = false

[window]
dimensions = { columns = 0, lines = 0 }
position = "None"
decorations = "Full"
padding = { x = 0, y = 0 }
dynamic_padding = false
opacity = 1.0
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
class = { general = "Alacritty" }
decorations_theme_variant = "None"
level = "Normal"

[scrolling]
history = 100000
multiplier = 1

[font]
size = 10.0
[font.normal]
family = "Hack"
style = "Regular"
[font.bold]
family = "Hack"
style = "Bold"
[font.italic]
family = "Hack"
style = "Italic"

[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#000000"
foreground = "#00ff00"
dim_foreground = "#004400"
bright_foreground = "#80ff80"

[colors.cursor]
text = "#000000"
cursor = "#00ff00"

[colors.selection]
text = "#00ff00"
background = "#1a4d1a"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#80ff80"

[colors.search]
matches = {foreground = "#000000", background = "#00aa00"}
focused_match = {foreground = "#000000", background = "#00ff00"}

[colors.hints]
start = {foreground = "#000000", background = "#80ff80"}
end = {foreground = "#000000", background = "#004400"}

[colors.line_indicator]
foreground = "#004400"
background = "#000000"

[colors.footer_bar]
foreground = "#00ff00"
background = "#003300"

[colors.normal]
black = "#000000"
red = "#FF0000"
green = "#008000"
yellow = "#FFFF00"
blue = "#0000FF"
magenta = "#FF00FF"
cyan = "#00FFFF"
white = "#FFFFFF"

[colors.bright]
black = "#808080"
red = "#FF8080"
green = "#80C080"
yellow = "#FFFF80"
blue = "#8080FF"
magenta = "#FF80FF"
cyan = "#80FFFF"
white = "#FFFFFF"

[colors.dim]
black = "#000000"
red = "#800000"
green = "#004000"
yellow = "#808000"
blue = "#000080"
magenta = "#800080"
cyan = "#008080"
white = "#808080"

[bell]
animation = "Linear"
duration = 150
color = "#80ff80"
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
style = {shape = "Beam", blinking = "Always"}
vi_mode_style = {shape = "Beam", blinking = "Always"}
blink_interval = 750
blink_timeout = 0
unfocused_hollow = true
thickness = 0.15

[terminal]
shell = "/usr/bin/zsh"
osc52 = "CopyPaste"

[mouse]
hide_when_typing = false

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
renderer = "None"
print_events = false
highlight_damage = false
prefer_egl = false